from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

try:
    from pip._vendor.packaging.requirements import Requirement
    from pip._vendor.packaging.utils import canonicalize_name
    from pip._vendor.packaging.version import InvalidVersion, Version
except Exception:  # pragma: no cover - fallback for non-pip Python installs
    from packaging.requirements import Requirement
    from packaging.utils import canonicalize_name
    from packaging.version import InvalidVersion, Version


@dataclass(frozen=True)
class Candidate:
    line: str
    source: Path
    order: int
    score: tuple[int, tuple[int, object]]


def clean_requirement_line(line: str) -> str:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or line[:1].isspace():
        return ""
    if stripped.startswith("-") or stripped.startswith("--"):
        return ""
    return re.split(r"\s+#", stripped, maxsplit=1)[0].strip()


def version_value(raw: str) -> tuple[int, object]:
    try:
        return (1, Version(raw))
    except InvalidVersion:
        return (0, raw.lower())


def requirement_score(requirement: Requirement) -> tuple[int, tuple[int, object]]:
    specifiers = list(requirement.specifier)
    if not specifiers:
        return (3, (1, Version("0")))

    exact_versions = [
        version_value(specifier.version)
        for specifier in specifiers
        if specifier.operator in {"==", "==="} and "*" not in specifier.version
    ]
    if exact_versions:
        return (2, max(exact_versions))

    lower_versions = [
        version_value(specifier.version)
        for specifier in specifiers
        if specifier.operator in {">=", ">"} and "*" not in specifier.version
    ]
    if lower_versions:
        return (1, max(lower_versions))

    return (0, (0, str(requirement.specifier)))


def requirement_key(requirement: Requirement) -> str:
    extras = ",".join(sorted(requirement.extras))
    marker = str(requirement.marker) if requirement.marker else ""
    return f"{canonicalize_name(requirement.name)}[{extras}];{marker}"


def merge_requirements(files: list[Path]) -> dict[str, Candidate]:
    merged: dict[str, Candidate] = {}
    order = 0

    for path in files:
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = clean_requirement_line(raw_line)
            if not line:
                continue

            order += 1
            requirement = Requirement(line)
            key = requirement_key(requirement)
            candidate = Candidate(
                line=str(requirement),
                source=path,
                order=order,
                score=requirement_score(requirement),
            )
            previous = merged.get(key)
            if previous is None or (candidate.score, candidate.order) > (
                previous.score,
                previous.order,
            ):
                merged[key] = candidate

    return merged


def display_path(path: Path, base: Path) -> str:
    try:
        return path.relative_to(base).as_posix()
    except ValueError:
        return path.as_posix()


def write_requirements(output: Path, files: list[Path], merged: dict[str, Candidate]) -> None:
    base = output.parent
    relative_files = [display_path(path, base) for path in files]
    lines = [
        "# This file is generated by Scripts/Merge-Requirements.py.",
        "# Re-run Setup.bat after updating submodules.",
        "#",
        "# Source files:",
    ]
    lines.extend(f"# - {path}" for path in relative_files)
    lines.append("")
    lines.extend(candidate.line for _, candidate in sorted(merged.items()))
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Merge project requirements.")
    parser.add_argument("files", nargs="+", type=Path)
    parser.add_argument("-o", "--output", required=True, type=Path)
    args = parser.parse_args()

    files = [path.resolve() for path in args.files]
    for path in files:
        if not path.is_file():
            raise FileNotFoundError(path)

    merged = merge_requirements(files)
    write_requirements(args.output.resolve(), files, merged)
    print(f"Wrote {len(merged)} requirements to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
